### ISSUE TITLE
panic: Tendermint state.AppHash does not match AppHash after replay

### ISSUE THREAD

**Issue by n3gtiv3** [cosmos/ethermint-archive#397] opened 2018-03-21 11:19 UTC
**BUG REPORT** :

**Tendermint version**  :  v0.14.0
**ethermint version**     :  0.5.3-deb7883
**go-ethereum version**:  1.6.7-stable

**Environment**:
- **OS** : Ubuntu 17.10

**What happened**:

Getting this error when starting tendermint for the second time. i.e when _block height_ is not  0

```
$tendermint --home ~/.ethermint/tendermint node
panic: Tendermint state.AppHash does not match AppHash after replay. Got 56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, expected 731C6D062E4C3BBAE068548F7454DE9760F9574B486A12C515178D8AB7C64F9E

```
```
Logs from tendermint before closing -
14:46
INFO [03-21|08:06:01] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=1.805ms   mgasps=0.000   number=2377 hash=731c6d…c64f9e
^Ccaptured interrupt, exiting...
```

Logs from ethermint before closing -

`
[03-21|02:36:01.349] Committed state                              module=state height=2377 txs=0 hash=731C6D062E4C3BBAE068548F7454DE9760F9574B486A12C515178D8AB7C64F9E`

**What you expected to happen**:

Since appHash is same as the last committed block hash, I am not sure why this is returning this error.

**How to reproduce it**:

1. Start tendermint and ethermint with block height 0 and let it commit few blocks.
2. Stop tendermint and ethermint.
3. Start tendermint node, it will return this error.

**Comment by d10r** [comment] 2018-03-27 09:35
Same issue here, running on Ubuntu 16.04.  
Happens independent of size of validator set (I tried with sets between 1 and 50 nodes).

**Comment by urugang** [comment] 2018-03-29 03:30
Ethermint has two AppHash, one is store in database for old, one is in memory for new, not finalized.  
When Commit, ethermint respond with old appHash, so tendermint stored old appHash.  
And when Info, ethermint respond with new appHash, not finalized.   
When restarting tendermint,  appHash from ethermint's Info is new and not finalized, appHash from tendermint's database is old and finalized.  

see [urugang/ethermint] (https://github.com/urugang/ethermint/commit/ff186526393ab25302bb3975aeac0714c36eb9ef)

**Comment by d10r** [comment] 2018-04-05 14:42
@urugang thanks!
could you please make a pull request out of it?

**Comment by EnchanterIO** [comment] 2018-06-08 08:18
Hey @d10r, @urugang I see u both fixed it int he same way. Are u running your version of ethermint somewhere in test/prod network?

I was able to pull your forked repo and fix my issue and I can confirm it's working but I am only running it on local for now. Will deploy it to a test network in cloud for my project soon and let you know how it works so ethermint can merge it later to the master.

**Comment by d10r** [comment] 2018-06-08 08:47
I just replicated the change of @urugang because it wasn't yet merged at the time.  
Worked fine in my tests (using https://github.com/lab10-coop/testnet-utils/tree/master/local-testnet/ethermint), but we didn't so far deploy it long term (testnet or production).

**Comment by urugang** [comment] 2018-06-11 04:01
Worked in my test network.
But somtime I still encounter 'AppHash mismatch' problem, so I think I just fixed one situation on initial run.

**Comment by EnchanterIO** [comment] 2018-06-21 09:41
Can confirm that the fix is not a stable one. I just encountered this issue once again. It will bit more complicated :)

**Comment by zramsay** [comment] 2018-07-11 18:44
see https://github.com/cosmos/ethermint for latest work on ethermint

**Closed as completed by zramsay** 2018-07-11 18:44 UTC
