### ISSUE TITLE
Can't install ethermint by using `make tools deps build`

### ISSUE THREAD

**Issue by jakeonchain** [cosmos/ethermint-archive#499] opened 2018-11-18 13:14 UTC
__System info:__ Current master abbe17db25675cc9cc7a62cc84c7b78580f323c7 Mac OS V 10.13.6
__Steps to reproduce:__

When I run `make tools deps build` as mentioned in the README.md file to setup `ethermint`, then I got 
```
--> Running dep ensure
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:

  ✗  github.com/hashicorp/golang-lru
  ✗  github.com/spf13/cobra

However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.

Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.




Root project is "github.com/tendermint/ethermint"
 10 transitively valid internal packages
 37 external packages imported from 6 projects
(0)   ✓ select (root)
(1)	? attempt github.com/cosmos/ethermint with 5 pkgs; 3 versions to try
(1)	    try github.com/cosmos/ethermint@master
(1)	✓ select github.com/cosmos/ethermint@master w/5 pkgs
(2)	? attempt github.com/pkg/errors with 1 pkgs; 11 versions to try
(2)	    try github.com/pkg/errors@v0.8.0
(2)	✓ select github.com/pkg/errors@v0.8.0 w/1 pkgs
```

__Expected behavior:__ I can install ethermint and start it

__Actual behavior:__ I can't install ethermint

__Additional info:__ log as above

Thanks for your help.

**Comment by alexanderbez** [comment] 2018-11-19 18:03
What is the exact issue here? Seems to be a duplicate of #500  which is now closed.

**Closed as completed by alexanderbez** 2018-11-19 18:03 UTC
